name: motivate_yourself
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_font_icons: ^2.2.5
  google_fonts: ^3.0.1
  expandable_bottom_sheet: ^1.1.1+1
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.0
  expandable: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  awesome_dialog: ^2.2.1
  syncfusion_flutter_gauges: ^20.2.40
  double_back_to_close_app: ^2.1.0
  top_snackbar_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter 

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  

  assets:
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  